POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NDUyZGMxY2YzMjUwOWY4MjBiMmZiZDMiLCJpYXQiOjE2ODMxNTIwNDl9.DcGcfNbGB1V2Yu2At3xeV648LZA0coqAdUelxhj-EfM

{
"title": "FullStack",
"author": "Eemeli Ahokas",
"url": "fullstackblog.com",
"likes": 7
}